### PR TITLE
fix(upload): failed to upload item icon color

### PR DESCRIPTION
**Pull request by inikolova**
Related to telerik/kendo-angular-upload#50

### CODE REVIEW

**Review by gyoshev — COMMENTED** [review]
I suspect this will need to be [applied to the bootstrap theme](https://github.com/telerik/kendo-theme-bootstrap/blob/v2/scss/upload/_theme.scss#L43), too? If so, it would be great if we can reuse these styles, [as mentioned earlier](https://github.com/telerik/kendo-theme-bootstrap/pull/73#discussion_r104916119). Is there a problem in providing variables and reusing the theme file?

**Comment by inikolova** [comment]
I believe that using variables is OK. @gyoshev , should I make the changes here or in a different branch / commit?

**Comment by gyoshev** [comment]
This branch is OK, the changes will be added to the PR, so we can continue the discussion.

**Review by joneff — APPROVED** [review]

**Comment by inikolova** [comment]
@gyoshev , I made the requested changes

**Comment by gyoshev** [comment]
We can merge after the variable name suggestions from the [theme-bootstrap issue](https://github.com/telerik/kendo-theme-bootstrap/pull/75#pullrequestreview-26554122) get fixed here.

**Review by gyoshev — APPROVED** [review]

**Pull request merged**
