### PR TITLE
fix: update grid layout to be usable by theme-bootstrap

### PR DESCRIPTION
**Pull request by joneff**
While vast, this refactoring is needed for Bootstrap theme to function properly.

### CODE REVIEW

**Comment by joneff** [comment]
Few screens to show the visual differences in theme-bootstrap and the lack of in theme-default

**theme-default**
before:
image

after:
image


**theme-bootstrap**
before:
image

after:
image

Don't mind the pager links in bootstrap theme. That's something entirely different

**Comment by inikolova** [comment]
Things, which should be fixed: 

- Grid headers, toolbar, filter row heights - should be 46px, currently are the same as the grid cells (36px);
- Grid with aggregates and frozen columns - the whole layout is broken. Also, the layout in the Grid / Export to Excel demo;
- Grid grouping header must have the same height in both cases - grouping applied and without grouping;
- Missing top border on k-group-cell;
- Grid headers don't show ellipsis when text overflows;
- Double border on the last row - grid with frozen columns and aggregates;
- Wrong padding on grid filter / column menu popups;
- Wrong border colors of grid headers in IE11;

**Review by inikolova — CHANGES_REQUESTED** [review]
Please see my comment

**Comment by joneff** [comment]
Grid header, toolbar etc height fixed by f8622878093ff77d5acc765cde9b46831c123c61

**Comment by joneff** [comment]
@inikolova I think I fixed all the points.

On a side note, since `flex` does not support `text-overflow: ellipsis` I switched to using `display: block` for same of the cases.

**Comment by gyoshev** [comment]
@joneff please rebase and resolve the conflicts. Also, the commit messages won't push a new version -- consider squashing to a `feat:` or `fix:` commit.

**Comment by inikolova** [comment]
After additional testing I observed the following: 

- _**k-grouping-header**_ is missing **display: block** definition;
- Currently **k-group-indicator** is 40px high while it should be the same as a regular button (30px); -> FIXED
- Grid **k-grouping-dropclue** is currently a vertical line, while it should have before / after elements; -> FIXED
- Wrong **.k-drag-clue** height -> FIXED

**Comment by gyoshev** [comment]
@inikolova added the display:block. It is specific to the angular rendering, as we don't use block elements.

**Review by gyoshev — APPROVED** [review]

**Review by inikolova — APPROVED** [review]

**Pull request merged**
