### PR TITLE
fix(combobox): clear button overlaps the selected item

### PR DESCRIPTION
**Pull request by inikolova**
Closes telerik/kendo-theme-default#261

### CODE REVIEW

**Review by gyoshev — COMMENTED** [review]
It's a bit confusing to encounter the RTL styles first, and have the default styles at the end of the file. Why not use the same selectors in both cases (`&.k-combobox-clearable`)?

**Comment by inikolova** [comment]
I added this rule at the end of the file in order to avoid unnecessarily increased specificity

**Comment by gyoshev** [comment]
Valid point. The specificity for the RTL styles can also be reduced by moving them to the clearable selector like this:
```
.k-combobox-clearable {
  .k-input {
      padding-right: $icon-size + $padding-x;
  }

  &[dir='rtl'] .k-input {
     padding-left: $icon-size + $padding-x;
     padding-right: $input-padding-x;
  }
}
```
This way the declarations will also be kept together.

**Comment by inikolova** [comment]
Isn't keeping all rtl styles in a single selector a better option?

**Comment by gyoshev** [comment]
Usually, yes. But it is more confusing to have overwriting styles (like the RTL ones) above the styles they override:

    .foo[dir='rtl'] { float: left; }
    .foo { float: right; }

**Pull request merged**
