### PR TITLE
Toolbar buttons fixes

### PR DESCRIPTION
**Pull request by magdalenaan**
related to split-button-fixes branch (https://github.com/telerik/kendo-theme-default/pull/278)

Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/89

### CODE REVIEW

**Comment by inikolova** [comment]
There is strange border applied to the toggle buttons

**Review by inikolova — COMMENTED** [review]
Тhere is а strange border applied to the toggle buttons;

**Comment by magdalenaan** [comment]
I cannot reproduce the issue. It is possible that is was fixed by fixing shadows. If the issue still persist, could you please provide some screenshot?

**Comment by inikolova** [comment]
Splitbutton active state differs from the design - currently it gets accent background

https://github.com/telerik/kendo-ux/blob/master/themes/default/buttons.psd

**Comment by magdalenaan** [comment]
Active state will be fixed after improving $button variables. Normal button should not have accent background in any of its states.

**Comment by inikolova** [comment]
@mvgmvg , please find a pictule which illustrates the strange border / shadow around toggle buttons
toggle_button

**Comment by joneff** [comment]
https://github.com/telerik/kendo-theme-default/pull/300 is related.

**Review by joneff — APPROVED** [review]

**Pull request merged**
