### PR TITLE
feat: add variables to disabled mixin

### PR DESCRIPTION
**Pull request by IanMuirhead**
#547 

Adds variables for the disabled mixin to allow for styling customization of the disabled state of components

Includes:
- opacity
- grayscale

### CODE REVIEW

**Comment by IanMuirhead** [comment]
@joneff Anyone able to put some thought into this pull request?

**Comment by gyoshev** [comment]
@IanMuirhead thank you for the contribution! The values can be handy when customizing the theme.

It seems that defining the complete filter (rather than the grayscale component) might be more flexible:

    $disabled-filter: grayscale(.1);

    filter: $disabled-filter;

This way, the filter function can also be changed (or completely disabled) with the variable. What do you think?

**Comment by joneff** [comment]
We could, perhaps, use a mixin for this and if the argument is not specified e.g. `null` not to output any styles at all.

**Comment by IanMuirhead** [comment]
@gyoshev Fair point - will make some modifications and update the pull request.

@joneff I had originally thought about using a mixin. Following the patterns elsewhere in the theme I thought variables would be more consistent.

**Review by joneff — APPROVED** [review]

**Comment by gyoshev** [comment]
@IanMuirhead thanks for the update! It has been merged into the development channel, and will be included in the next release of the theme. :tada:

**Pull request merged**
