### PR TITLE
fix: streamline window and dialog layout

### PR DESCRIPTION
**Pull request by joneff**

### CODE REVIEW

**Comment by gyoshev** [comment]
It would be best to merge this alongside the fixes for https://github.com/telerik/kendo-angular-dialog/issues/30

**Comment by joneff** [comment]
When we merge this, the code should take care of #158

**Comment by joneff** [comment]
Should also take care of #179.

**Comment by gyoshev** [comment]
Current rendering is Safari collapses the content and still aligns buttons to the left. Seems to be a flexbox issue.

image

**Comment by joneff** [comment]
Somewhat related to #158

**Comment by joneff** [comment]
@gyoshev merging the PR. We already have an issue for the dialog layout.

**Pull request merged**
