### PR TITLE
Extend variables

### PR DESCRIPTION
**Pull request by joneff**
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/245

Add global options variables for box-shadow, border-radius, gradients and transitions

### CODE REVIEW

**Comment by cornillemichiel** [comment]
I noticed the variables added in 254b611c03e7c590675c89b5aa1f6fa8503ed427 all have the _true_ default. In the bootstrap scss files shadows and gradients are set to _false_

**Comment by joneff** [comment]
The way we've set up the themes to work is that theme-bootstrap (and any other theme) pulls mixins, but not variables, from theme-default. So we first need to make the mixins work for theme-default and then apply them to theme-bootstrap.

In terms, the variables in the said commit will apply only for theme-default. When this PR is closed, we'll add the same set of variables for theme-bootstrap which will respect values from bootstrap.

**Comment by joneff** [comment]
@gyoshev, @inikolova, @mvgmvg  the question remains should we enforce `border-radius: 0` when the flag is false, or should we not apply border radius at all? The same goes for the rest of the flags.

@cornillemichiel it will be interesting to hear what you think about that question.

**Comment by cornillemichiel** [comment]
Okay that makes sense thanks for the clarification.

**Comment by cornillemichiel** [comment]
I'll get back to you on your second question

**Comment by cornillemichiel** [comment]
@joneff I'd defo prefer no border radius at all. The less the framework gets in the way of customization the better. Also, less bytes to send over the wire 👍

**Comment by inikolova** [comment]
@joneff, I prefer no border radius at all, too

**Comment by joneff** [comment]
While we are still on the topic of `border-radius`, per say, should we go with a single value or add a per-component value, say `$button-border-radius: $border-radius !default`?

**Comment by inikolova** [comment]
Using a single value sounds better to me, as all components have the same border-radius

**Review by inikolova — APPROVED** [review]

**Pull request merged**
